import './styles.module.scss'
import { FirebaseNextJSProvider } from 'firebase-nextjs/client/auth'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<FirebaseNextJSProvider>
				<body style={{ margin: 0 }}>{children}</body>
			</FirebaseNextJSProvider>
		</html>
	)
}
